# Generated by Django 5.1.4 on 2024-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('time_scanned', models.DateTimeField(auto_now_add=True)),
                ('sender_address', models.TextField()),
                ('receiver_address', models.TextField()),
                ('receiver_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('receiver_state', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_district', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('modified_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
